### PR TITLE
Github Searchsource

### PR DESCRIPTION
**Pull request by edensarrival**
Added an searchsource to search github. Using  an accesstoken provided by github.
Functionality to search for repository title, readme content and both combined on github.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Working as expected.

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

(https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)

### CODE REVIEW

**Comment by geritwagner** [comment]
Thank you for implementing the API-search for GitHub!

I have just added the PyGithub dependency and the test-minimal-deps now passes.

Currently, the other tests fail due to a modification in `colrev/record/record_identifier.py`. If you undo these changes, that should fix this part of the tests. GitHub also indicates that there should be commas between the author dictionaries in  `colrev/packages/github/pyproject.toml`, and the pre-commit hooks show a few warnings ([here](https://results.pre-commit.ci/run/github/363073613/1719328467.gnpzTheXQJunCvhgnt3j1g)). Could you have a look at them and fix them?

**Comment by geritwagner** [comment]
Thank you for the fixes. I have removed the poetry.lock temporarily to see whether the tests pass. Do you know how to fix the remaining [issues](https://results.pre-commit.ci/run/github/363073613/1719396568.JIRrvLP1Qa23dgtNESQg9g)?

**Comment by k-schnickmann** [comment]
The remaining issues should be resolved now. Please let us know if you encounter any further problems, and we’d be happy to address them.

**Comment by geritwagner** [comment]
Thank you for implementing the changes! Your work should be ready to merge. I do not have any additional suggestions, but will leave this pull request open until next week.

**Comment by geritwagner** [comment]
### Search:
- [x] No intermediate messages are printed when the search is executed. This could be solved by integrating the loops in the search method.

### Code:
- [x] Search method is too long and shoudl be refactored.
- [x] Add-endpoint: Unnecessary if statement for http.
- [x] Add-endpoint: Parameter input should be refactored (too many indentations).

### Documentation:
- [ ] Does not explain the individual user inputs.
- [x] No information on the API key, where it can be created.
- [ ] No overview of the links that might be useful for the user.

### No error handling for API key:
- [x] Program crashes if no API key is present or it is incorrect.

**Comment by geritwagner** [comment]
@all-contributors
please add @k-schnickmann for code. 
please add @koljarinne for code.
please add @edensarrival for code.
please add @U1TIM4T3 for code.

**Comment by geritwagner** [comment]
https://github.com/all-contributors
please add @U1TIM4T3 for code.

**Comment by geritwagner** [comment]
@all-contributors please add @U1TIM4T3 for code.

**Comment by geritwagner** [comment]
Everything should be ready to merge 🎉 🍾 🎈 Thank you for your contribution to CoLRev!

**Pull request merged**
