### PR TITLE
OSF SearchSource

### PR DESCRIPTION
**Pull request by pmao0907**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #360 

## What is the new behavior?

- API search with OSF REST-API
- Documentation of OSF-SearchSource
-

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by geritwagner** [comment]
Thank you for implementing the API-search for OSF!

With minor changes, I was able to run the code and retrieve records. I noticed that there are some unnecessary files in the [pull request](https://github.com/CoLRev-Environment/colrev/pull/471/files). In particular, the `colrev/colrev/packages/osf_search_source` could be removed (this should also fix the tests). In addition, there are a few unnecessary attributes (maybe even methods) in the `OSFApiQuery` class. Could you have a look at these items and streamline the code a bit?

**Comment by pmao0907** [comment]
Thank you for the changes! We've reviewed our code and made some changes of run_api_query() again, because without these we can't retrieve the records properly on our machine. Unnecessary items in osf.api are deleted. 

Let us know if you have more suggestions!

**Comment by geritwagner** [comment]
Good work - thank you for updating the code and testing everything again. I just pushed a few additional changes. You could add your names to the author list in `colrev/packages/osf/pyproject.toml` if you like.  I do not have any additional suggestions, and your work should be ready to merge. Please note that I will leave this pull request open until next week.

**Comment by geritwagner** [comment]
**Feedback provided by students**

- [ ] Remove the duplicate assignment of OSFApiQuery in line 191.
- [ ] Address pylint and pre-commit messages, for example the "is None" warning, to improve code quality.
- [ ] Rename helper methods in osf_api.py with underscore prefixes and move them into one method.
- [ ] Refactor the build_url method in osf_api.py for clarity and functionality.

**Pull request merged**
